[DOCS, GV, AI, SSL-VISION, DOCKER] Updated documentation, made GV work on fetdatorn, add GV demo scenario to AI, correct SSL-Vision setup (#23)
DOCS:
 - I rewrote some docs to better reflect our current setup of a mono-repo

GV:
-  I've fixed the backend/frontend scripts to make sure the website works on both fetdatorn and locally for running simulations
-  I fixed the robots table to display the last value if no new value were grabbed from SSL vision (so that the robot table doesn't flash when don't get data, like the robots on the fields do).

AI:
-    Added GameViewer scenario to use when developing for the gameviewer
 -   Removed connecting to ersim isntead of 127.0.0.1 from config, see changes to DOCKER below.

SSL Vision:
 - Working setup of SSL vision (confirmed on fetdatorn), some ugly hacks to get GV to work with fetdatorn, should be cleaned up in the future (I've added to my todo), not necessary though.

DOCKER:
-    Always use network mode host, never use docker network. This makes it easier to have one common setup for simulation and for fetdatorn.

diff --git a/scripts/bin/sg-enter b/scripts/bin/sg-enter
--- a/scripts/bin/sg-enter
+++ b/scripts/bin/sg-enter
@@ -8,11 +8,17 @@ if [ -z "$CONTAINERS" ]; then
 fi
 
 if [ -n "$1" ]; then
-    docker exec -it "$1" /bin/bash
+    if [[ -n "${CONTAINERS[$1]}" ]]; then
+        docker exec -it "${CONTAINERS[$1]}" /bin/bash
+    else
+        echo -e "${RED}Invalid container index: $1${NC}"
+        exit 1
+    fi
     exit 0
 fi
 
 echo -e "${ORANGE}Select a container to enter:${NC}"
+
 for i in "${!CONTAINERS[@]}"; do
     echo -e "${ORANGE}[$i] ${CONTAINERS[$i]}${NC}"
 done
